### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Tuvqlu** [Arisify/Skywar#3]
How to create a game
/sw addmap doesn’t do anything

**Comment by RandomNonDev** [comment]
i think its still in beta

**Comment by RandomNonDev** [comment]
> How to create a game /sw addmap doesn’t do anything

Read the file "ReadMe.md" look at commands

**Comment by NTT1906** [comment]
I'm sorry for not realizing these issues sooner, yeah the plugin is in development. I'm having some exams now so I cannot finish it rather than giving it a form to understand it later. I'm sorry for your inconvenience!

**Comment by Tuvqlu** [comment]
Of course! Take your time! All the features look really cool and I am excited to see the end product! 

Make sure you study though! Get good grades on those exams! Good luck!
